Feature/homework 1
suppadu/FocusStartHomeworks pull request #1
Opened 2021-04-20 06:10 UTC by suppadu

Выполненное ДЗ №1 (Учет автомобилей)
Чтобы добавить новый авто в список, нужно нажать на + в правой части экрана. Новый авто автоматически отобразится в списке.
Чтобы отсортировать список авто по типу кузова, нужно нажать на кнопку с машинами в левой части экрана

2021-04-20 13:00 UTC, tratotul007 requested changes

2021-04-20 13:00 UTC, Tratotul commented on FSHW1_CarCount/FSHW1_CarCount/AddCarViewController.swift
> +        print(newCar!)
ForceUnwrap не используем

2021-04-20 13:00 UTC, Tratotul commented on FSHW1_CarCount/FSHW1_CarCount/SceneDelegate.swift
> +    }
Лишнее надо убрать

2021-04-20 13:00 UTC, tratotul007 commented on FSHW1_CarCount/FSHW1_CarCount/AddCarViewController.swift
> +        pickerView.delegate = self
self.pickerView нужно тут везде использовать self. это облегчает понимание

2021-04-20 13:13 UTC, suppadu commented on FSHW1_CarCount/FSHW1_CarCount/AddCarViewController.swift
> +        print(newCar!)
`body: Car.Body.init(rawValue: bodyTextField.text!) ?? Car.Body.SUV`

Здесь возможно использование? Тут init сам является опционалом и дальше идет использование default значения. Или все таки следует удлинить код по сути самоповтором?

2021-04-25 06:44 UTC, tratotul007 approved these changes
Сделай правки и мержи

2021-04-25 06:44 UTC, Tratotul commented on FSHW1_CarCount/FSHW1_CarCount/AddCarViewController.swift
> +        print(newCar!)
Тут проблема в том что у тебя в bodyTextField.text будет nil, то просто приложение упадет, как раз таки из-за `!`

2021-04-25 06:44 UTC, tratotul007 commented on FSHW1_CarCount/FSHW1_CarCount/Car.swift
> +    enum Body: String, CaseIterable {
энум среди хранимых свойств, убери его выше, над пропертями

2021-04-25 06:44 UTC, tratotul007 commented on FSHW1_CarCount/FSHW1_CarCount/Car.swift
> +    enum Body: String, CaseIterable {
И кейсы с маленькой буквы у энумов

2021-04-25 06:44 UTC, tratotul007 commented on FSHW1_CarCount/FSHW1_CarCount/AddCarViewController.swift
> +
ок, но тебе самому глаз не режет?? или в икскоде это цветным квадратиком отображается?)

2021-04-25 06:44 UTC, tratotul007 commented on FSHW1_CarCount/FSHW1_CarCount/AppDelegate.swift
> +    }
Лишнее надо убирать

2021-04-25 07:06 UTC, suppadu commented on FSHW1_CarCount/FSHW1_CarCount/AddCarViewController.swift
> +
Да, это цветные квадратики в икскоде)

2021-04-25 12:15 UTC, merged